FROM ubuntu:latest
ENV NODE_VERSION=22

WORKDIR /pulse-editor/server

# Install basic tools
RUN apt update && apt install -y curl make python3 build-essential git zip unzip ca-certificates gnupg && rm -rf /var/lib/apt/lists/*

# Install node

# Add NodeSource repository for Node.js 22
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -

# Install Node.js
RUN apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY . /pulse-editor/server

# Clone https://github.com/shellishack/supergateway repository
# RUN git clone https://github.com/shellishack/supergateway /pulse-editor/server/src/lib/supergateway

# install pulse-cli
RUN npm install -g @pulse-editor/cli@beta

# install dependencies
RUN npm install

# build project
RUN npm run build

# Generate self-signed certificate
# RUN bash -c "./utils/generate-self-signed.sh"

EXPOSE 6080 6443

CMD ["npm", "run", "start"]
