FROM ubuntu:latest
ENV NODE_VERSION=20

WORKDIR /app

# install curl
RUN apt update && apt install -y curl make python3 build-essential

# install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# set env
ENV NVM_DIR=/root/.nvm

COPY . /app

# install node
RUN bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && npm install && npm run build"

# Generate self-signed certificate
# RUN bash -c "./utils/generate-self-signed.sh"

# set ENTRYPOINT for reloading nvm-environment
ENTRYPOINT ["bash", "-c", "source $NVM_DIR/nvm.sh && exec \"$@\"", "--"]

EXPOSE 6080 6443

CMD ["npm", "run", "start"]
