import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import vibeDevFlowSidebar from "./docs/api-reference/app-server-functions/official-apps/vibe-dev-flow/sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guideSidebar: [{ type: "autogenerated", dirName: "guide" }],
  apiRefSidebar: [
    {
      type: "doc",
      label: "Get Started",
      id: "api-reference/index",
    },
    {
      type: "doc",
      label: "Get Pulse Editor API Key",
      id: "api-reference/get-pulse-editor-api-key",
    },
    {
      type: "category",
      label: "App Server Functions APIs",

      items: [
        {
          type: "doc",
          label: "Introduction",
          id: "api-reference/app-server-functions/introduction",
        },
        {
          type: "category",
          label: "Official Apps APIs",
          link: {
            type: "doc",
            id: "api-reference/app-server-functions/official-apps/index",
          },
          items: [
            {
              type: "category",
              label: "Vibe Dev Flow",
              items: vibeDevFlowSidebar,
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
