name: Build Desktop

on:
  pull_request:
    branches: ["main"]
    paths:
      - "desktop/**"
      - "web/**"
      - ".github/workflows/build-desktop.yml"

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install shared-utils dependencies
        run: npm install --workspace=npm-packages/shared-utils

      - name: Build shared-utils
        run: npm run shared-utils-build

      - name: Install capacitor-plugin dependencies
        run: npm install --workspace=capacitor-plugin

      - name: Build capacitor-plugin
        run: npm run capacitor-plugin-build

      - name: Install web dependencies
        run: npm install --workspace=web

      - name: Install desktop dependencies
        run: npm install --workspace=desktop

      - name: Rebuild native modules
        run: npm run rebuild-native --workspace=desktop

      - name: Build Electron App
        run: |
          npm run desktop-build
