name: Build Mobile

env:
  ANDROID_SDK_VERSION: "35.0.0"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
      - "android/**"
      - ".github/workflows/build-mobile.yml"

jobs:
  build:
    strategy:
      matrix:
        target: [android]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK build tools
        run: |
          sdkmanager "build-tools;${{env.ANDROID_SDK_VERSION}}"
          echo "$ANDROID_SDK_ROOT/build-tools/${{env.ANDROID_SDK_VERSION}}" >> $GITHUB_PATH

      - name: Get Keystore
        run: |
          mkdir .keystore 
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode > android/.keystore/keystore.jks

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install web dependencies
        run: npm install --workspace=web

      - name: Install mobile dependencies
        run: npm install --workspace=mobile

      - name: Build Web App
        run: npm run build

      - name: Change Android Project Permission
        run: chmod +x android/gradlew

      - name: Sync Capacitor App
        run: npx cap sync

      - name: Build Capacitor App
        run: npx cap build android --keystorepath .keystore/keystore.jks --keystorepass ${{ secrets.ANDROID_KEYSTORE_PASS }} --androidreleasetype APK
