name: Release Pulse CLI

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i
        working-directory: npm-packages/cli

      - name: Build @pulse-editor/cli
        run: npm run build
        working-directory: npm-packages/cli

      - name: Set up npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        working-directory: npm-packages/cli
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public
        working-directory: npm-packages/cli
