# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release NPM Package (Alpha)

on:
  push:
    branches: ["dev"]

env:
  RELEASE_TAG: alpha

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i --workspace=npm-packages/shared-utils && npm i --workspace=npm-packages/react-api

      - name: Build @pulse-editor/shared-utils
        run: npm run build --workspace=npm-packages/shared-utils

      - name: Build @pulse-editor/react-api
        run: npm run build --workspace=npm-packages/react-api

      - name: Install changesets
        run: npm i -D changesets

      - name: Use Alpha Changesets Tag
        run: npx changeset pre enter ${{env.RELEASE_TAG}}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npx changeset version
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
